name: TruffleHog Scan Test

on:
    # push:
    #     branches:
    #         - feat/Trufflehog
    pull_request:
        branches:
            - main

jobs:
    trufflehog:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            # -   name: Set up TruffleHog
            #     run: |
            #       docker pull trufflesecurity/trufflehog:latest

            -   name: Run TruffleHog
                continue-on-error: false  # Certifica que o workflow falha ao encontrar segredos
                run: |
                  docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://github.com/danilocasabona/3361-Curso-4-AppSec